/* ============================================================
   server/utils/report-layouts.js — legacy_tabular renderer

   legacy_tabular is the platform built-in, always-resolvable fallback
   (report-card-templates.js's resolveTemplate) — any school that has
   never explicitly assigned a template default lands here, not just
   pre-engine snapshots. It was frozen when RCE1's remark/observation
   toggles shipped for the two newer layouts (subject_paired, marks_
   then_comments) and never got the same treatment — reported directly:
   turning off Principal's Comment still left its label and an empty
   box on the page, and Observation Ratings never appeared at all
   regardless of the toggle. Covers those fixes, plus the separate
   subject-name-not-id bug (also reported directly: "just seeing their
   ids") and the stray "Generated by Msingi..." cover line removed per
   an explicit request (redundant with the school's own customisable
   footerNote + date already in the real footer).

   Builds real IR via report-cards.js's _computeReportSections, same
   integration point report-layouts-subject-paired.test.js uses.
   ============================================================ */
'use strict';

jest.mock('../middleware/auth', () => ({ authMiddleware: (_r, _s, n) => n() }));
jest.mock('../middleware/rbac', () => ({ rbac: () => (_r, _s, n) => n() }));
jest.mock('../middleware/plan', () => ({ planGate: () => (_r, _s, n) => n() }));
jest.mock('../utils/archival', () => ({ isYearArchived: jest.fn().mockResolvedValue(false) }));

const reportCardsRouter = require('../routes/report-cards');
const { LAYOUTS } = require('../utils/report-layouts');

function makeSpyDoc() {
  const calls = [];
  const spy = { page: { width: 595.28, height: 841.89 } };
  const methods = [
    'addPage', 'rect', 'roundedRect', 'circle', 'fill', 'stroke', 'fillColor', 'fontSize',
    'font', 'text', 'image', 'save', 'translate', 'rotate', 'fillOpacity', 'restore', 'moveTo', 'lineTo',
  ];
  for (const m of methods) {
    spy[m] = (...args) => { calls.push({ method: m, args }); return spy; };
  }
  spy.heightOfString = (text, opts = {}) => {
    const width = opts.width || 400;
    const charsPerLine = Math.max(10, Math.floor(width / 5));
    const lines = Math.max(1, Math.ceil(String(text ?? '').length / charsPerLine));
    return lines * 12;
  };
  return { spy, calls };
}

function baseSnap(overrides = {}) {
  return {
    status: 'published', superseded: false, version: 1,
    studentName: 'Jane Doe', admissionNo: 'ADM001', className: 'Grade 7',
    streamName: 'East', houseName: 'Red House',
    termName: 'Term 2', academicYear: '2026', termNumber: 2, schoolName: 'Test School',
    studentPhotoUrl: null,
    assessmentWeights: [{ assessmentType: 'cat', label: 'CAT', weight: 40 }, { assessmentType: 'exam', label: 'Exam', weight: 60 }],
    gradingSchema: [{ min: 0, grade: 'A', points: 12, label: 'Excellent' }],
    subjects: {
      math: { finalScore: 85, grade: 'A', breakdown: { cat: 80, exam: 88 }, remarks: 'Excellent work' },
      english: { finalScore: 55, grade: 'C', breakdown: { cat: 50, exam: 58 } },
    },
    totalScore: 140, averageScore: 70, gpa: 3.2,
    rankings: { class: { rank: 2, outOf: 30 } },
    comments: {
      classTeacherName: 'Mrs. Otieno', principalName: 'Dr. Kariuki',
      classTeacherRemark: 'Good progress this term.', principalRemark: 'Keep it up.',
      subjectComments: { math: 'Strong grasp of algebra.', english: 'Needs more reading practice.' },
    },
    ...overrides,
  };
}

function computeSections(snapOverrides = {}, config = {}, extra = {}) {
  return reportCardsRouter._computeReportSections(
    baseSnap(snapOverrides), { rankingEnabled: true, ...config }, null,
    { subjectTeacherCommentsEnabled: true, ...extra }
  );
}

describe('legacy_tabular.renderPdf — remark boxes now honour their toggles', () => {
  test('both boxes draw by default (showClassTeacherRemark/showPrincipalRemark default true)', () => {
    const { spy, calls } = makeSpyDoc();
    LAYOUTS.legacy_tabular.renderPdf(spy, computeSections(), {}, true);
    const texts = calls.filter(c => c.method === 'text').map(c => c.args[0]);
    expect(texts).toContain("CLASS TEACHER'S REMARK:");
    expect(texts).toContain("PRINCIPAL'S COMMENT:");
    expect(texts).toContain('Good progress this term.');
    expect(texts).toContain('Keep it up.');
  });

  test('turning Principal\'s Comment off removes its label AND its box — no blank area left behind', () => {
    const { spy, calls } = makeSpyDoc();
    const sections = computeSections({}, { showPrincipalRemark: false });
    LAYOUTS.legacy_tabular.renderPdf(spy, sections, {}, true);
    const texts = calls.filter(c => c.method === 'text').map(c => c.args[0]);
    expect(texts).not.toContain("PRINCIPAL'S COMMENT:");
    expect(texts).not.toContain('Keep it up.');
    // Class teacher's box is untouched by the other toggle.
    expect(texts).toContain("CLASS TEACHER'S REMARK:");
  });

  test('turning Class Teacher\'s Remark off removes only that box', () => {
    const { spy, calls } = makeSpyDoc();
    const sections = computeSections({}, { showClassTeacherRemark: false });
    LAYOUTS.legacy_tabular.renderPdf(spy, sections, {}, true);
    const texts = calls.filter(c => c.method === 'text').map(c => c.args[0]);
    expect(texts).not.toContain("CLASS TEACHER'S REMARK:");
    expect(texts).toContain("PRINCIPAL'S COMMENT:");
  });

  test('both off removes both, and the signature line moves up to reclaim the space (fewer rect calls at the old Y)', () => {
    const { spy, calls } = makeSpyDoc();
    const sections = computeSections({}, { showClassTeacherRemark: false, showPrincipalRemark: false });
    LAYOUTS.legacy_tabular.renderPdf(spy, sections, {}, true);
    const texts = calls.filter(c => c.method === 'text').map(c => c.args[0]);
    expect(texts).not.toContain("CLASS TEACHER'S REMARK:");
    expect(texts).not.toContain("PRINCIPAL'S COMMENT:");
    expect(texts).not.toContain('Good progress this term.');
    expect(texts).not.toContain('Keep it up.');
  });
});

describe('legacy_tabular.renderHtml — remark boxes now honour their toggles', () => {
  test('both render by default', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections());
    expect(html).toContain('Good progress this term.');
    expect(html).toContain('Keep it up.');
  });

  test('each toggle independently removes its own block, not both', () => {
    const onlyPrincipal = LAYOUTS.legacy_tabular.renderHtml(computeSections({}, { showClassTeacherRemark: false }));
    expect(onlyPrincipal).not.toContain('Good progress this term.');
    expect(onlyPrincipal).toContain('Keep it up.');

    const onlyClassTeacher = LAYOUTS.legacy_tabular.renderHtml(computeSections({}, { showPrincipalRemark: false }));
    expect(onlyClassTeacher).toContain('Good progress this term.');
    expect(onlyClassTeacher).not.toContain('Keep it up.');
  });
});

describe('legacy_tabular — subject names, not raw subjectIds (reported: "just seeing their ids")', () => {
  test('the results table and the subject-comments table both show the resolved name', () => {
    const sections = computeSections({}, {}, { subjectNames: { math: 'Mathematics', english: 'English Language' } });
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html).toContain('Mathematics');
    expect(html).toContain('English Language');
    expect(html).not.toContain('>math<');
    expect(html).not.toContain('>english<');
  });

  test('falls back to the raw id if a subject has no resolvable name (e.g. deleted after the snapshot was taken)', () => {
    const sections = computeSections({}, {}, { subjectNames: {} });
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html).toContain('math');
    expect(html).toContain('english');
  });

  test('same fix applies to the PDF path', () => {
    const { spy, calls } = makeSpyDoc();
    const sections = computeSections({}, {}, { subjectNames: { math: 'Mathematics', english: 'English Language' } });
    LAYOUTS.legacy_tabular.renderPdf(spy, sections, {}, true);
    const texts = calls.filter(c => c.method === 'text').map(c => c.args[0]);
    expect(texts.some(t => String(t).includes('Mathematics'))).toBe(true);
    expect(texts.some(t => String(t) === 'math')).toBe(false);
  });
});

describe('legacy_tabular.renderHtml — Observation Ratings now actually appear', () => {
  test('never shown when the school has not turned it on (default)', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections());
    expect(html).not.toContain('Class Teacher Observations');
  });

  test('shown with the saved rating when turned on', () => {
    const sections = computeSections(
      { comments: { ...baseSnap().comments, observationRatings: { Teamwork: 'good' } } },
      { showObservationRatings: true, observationCategories: ['Teamwork', 'Confidence'] },
    );
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html).toContain('Class Teacher Observations');
    expect(html).toContain('Teamwork');
    expect(html).toContain('Confidence');
  });
});

describe('legacy_tabular.renderHtml — Behaviour page is skipped, not shown empty', () => {
  test('no forced page, no "No behaviour records" placeholder, when there is nothing to show', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections());
    expect(html).not.toContain('BEHAVIOUR REPORT');
    expect(html).not.toContain('No behaviour records found');
  });

  test('renders normally when there is real behaviour data', () => {
    const sections = computeSections({}, { showBehaviour: true }, {
      behaviour: { merits: 5, demerits: 1, points: 4, total: 6 },
    });
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html).toContain('BEHAVIOUR REPORT');
    expect(html).toContain('Merits');
  });
});

describe('legacy_tabular.renderHtml — no stray "Generated by Msingi" line on the cover', () => {
  test('the cover no longer carries this hardcoded, non-customisable text', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections());
    expect(html).not.toContain('Generated by Msingi');
  });

  test('the shared cover (subject_paired/marks_then_comments) is also clean', () => {
    expect(LAYOUTS.subject_paired.renderHtml(computeSections())).not.toContain('Generated by Msingi');
    expect(LAYOUTS.marks_then_comments.renderHtml(computeSections())).not.toContain('Generated by Msingi');
  });

  test('the real, customisable footer message and date are still present', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections({}, { footerNote: 'This report is unofficial unless signed and/or stamped by a school official.' }));
    expect(html).toContain('This report is unofficial unless signed and/or stamped by a school official.');
    expect(html).toMatch(/Generated:/);
  });
});

describe('legacy_tabular.renderHtml — principal signature & school stamp (reported: "the stamp and principal\'s signature didn\'t show")', () => {
  test('neither image appears when the school has uploaded neither', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections());
    expect(html).not.toContain('<img');
  });

  test('a published snapshot\'s own frozen URLs render as <img> tags', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(
      computeSections({ principalSignatureUrl: 'data:image/png;base64,AAAA', schoolStampUrl: 'data:image/png;base64,BBBB' })
    );
    expect(html).toContain('<img src="data:image/png;base64,AAAA"');
    expect(html).toContain('<img src="data:image/png;base64,BBBB"');
  });

  test('falls back to the live school profile when the snapshot has none of its own (unpublished draft preview)', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(
      computeSections({}, {}, { school: { principalSignatureUrl: 'data:image/png;base64,CCCC', schoolStampUrl: 'data:image/png;base64,DDDD' } })
    );
    expect(html).toContain('<img src="data:image/png;base64,CCCC"');
    expect(html).toContain('<img src="data:image/png;base64,DDDD"');
  });

  test('the snapshot\'s own frozen URL wins over a later live school-profile change', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(
      computeSections(
        { principalSignatureUrl: 'data:image/png;base64,FROZEN' },
        {},
        { school: { principalSignatureUrl: 'data:image/png;base64,CHANGED_SINCE' } },
      )
    );
    expect(html).toContain('<img src="data:image/png;base64,FROZEN"');
    expect(html).not.toContain('CHANGED_SINCE');
  });

  test('turning off Principal\'s Comment removes the signature image too — it has nowhere left to sit', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(
      computeSections({ principalSignatureUrl: 'data:image/png;base64,AAAA', schoolStampUrl: 'data:image/png;base64,BBBB' }, { showPrincipalRemark: false })
    );
    expect(html).not.toContain('<img');
  });

  test('same fix applies to the PDF path', () => {
    const { spy, calls } = makeSpyDoc();
    const sections = computeSections();
    LAYOUTS.legacy_tabular.renderPdf(spy, sections, { principalSignature: Buffer.from('x'), schoolStamp: Buffer.from('y') }, true);
    expect(calls.some(c => c.method === 'image')).toBe(true);
  });
});
