/* ============================================================
   server/utils/report-layouts.js — legacy_tabular renderer

   legacy_tabular is the platform built-in, always-resolvable fallback
   (report-card-templates.js's resolveTemplate) — any school that has
   never explicitly assigned a template default lands here, not just
   pre-engine snapshots. It was frozen when RCE1's remark/observation
   toggles shipped for the two newer layouts (subject_paired, marks_
   then_comments) and never got the same treatment — reported directly:
   turning off Principal's Comment still left its label and an empty
   box on the page, and Observation Ratings never appeared at all
   regardless of the toggle. Covers those fixes, plus the separate
   subject-name-not-id bug (also reported directly: "just seeing their
   ids") and the stray "Generated by Msingi..." cover line removed per
   an explicit request (redundant with the school's own customisable
   footerNote + date already in the real footer).

   Builds real IR via report-cards.js's _computeReportSections, same
   integration point report-layouts-subject-paired.test.js uses.
   ============================================================ */
'use strict';

jest.mock('../middleware/auth', () => ({ authMiddleware: (_r, _s, n) => n() }));
jest.mock('../middleware/rbac', () => ({ rbac: () => (_r, _s, n) => n() }));
jest.mock('../middleware/plan', () => ({ planGate: () => (_r, _s, n) => n() }));
jest.mock('../utils/archival', () => ({ isYearArchived: jest.fn().mockResolvedValue(false) }));

const reportCardsRouter = require('../routes/report-cards');
const { LAYOUTS } = require('../utils/report-layouts');

function makeSpyDoc() {
  const calls = [];
  const spy = { page: { width: 595.28, height: 841.89 } };
  const methods = [
    'addPage', 'rect', 'roundedRect', 'circle', 'fill', 'stroke', 'fillColor', 'fontSize',
    'font', 'text', 'image', 'save', 'translate', 'rotate', 'fillOpacity', 'restore', 'moveTo', 'lineTo',
  ];
  for (const m of methods) {
    spy[m] = (...args) => { calls.push({ method: m, args }); return spy; };
  }
  spy.heightOfString = (text, opts = {}) => {
    const width = opts.width || 400;
    const charsPerLine = Math.max(10, Math.floor(width / 5));
    const lines = Math.max(1, Math.ceil(String(text ?? '').length / charsPerLine));
    return lines * 12;
  };
  return { spy, calls };
}

function baseSnap(overrides = {}) {
  return {
    status: 'published', superseded: false, version: 1,
    studentName: 'Jane Doe', admissionNo: 'ADM001', className: 'Grade 7',
    streamName: 'East', houseName: 'Red House',
    termName: 'Term 2', academicYear: '2026', termNumber: 2, schoolName: 'Test School',
    studentPhotoUrl: null,
    assessmentWeights: [{ assessmentType: 'cat', label: 'CAT', weight: 40 }, { assessmentType: 'exam', label: 'Exam', weight: 60 }],
    gradingSchema: [{ min: 0, grade: 'A', points: 12, label: 'Excellent' }],
    subjects: {
      math: { finalScore: 85, grade: 'A', breakdown: { cat: 80, exam: 88 }, remarks: 'Excellent work' },
      english: { finalScore: 55, grade: 'C', breakdown: { cat: 50, exam: 58 } },
    },
    totalScore: 140, averageScore: 70, gpa: 3.2,
    rankings: { class: { rank: 2, outOf: 30 } },
    comments: {
      classTeacherName: 'Mrs. Otieno', principalName: 'Dr. Kariuki',
      classTeacherRemark: 'Good progress this term.', principalRemark: 'Keep it up.',
      subjectComments: { math: 'Strong grasp of algebra.', english: 'Needs more reading practice.' },
    },
    ...overrides,
  };
}

function computeSections(snapOverrides = {}, config = {}, extra = {}) {
  return reportCardsRouter._computeReportSections(
    baseSnap(snapOverrides), { rankingEnabled: true, ...config }, null,
    { subjectTeacherCommentsEnabled: true, ...extra }
  );
}

describe('legacy_tabular.renderPdf — remark boxes now honour their toggles', () => {
  test('both boxes draw by default (showClassTeacherRemark/showPrincipalRemark default true)', () => {
    const { spy, calls } = makeSpyDoc();
    LAYOUTS.legacy_tabular.renderPdf(spy, computeSections(), {}, true);
    const texts = calls.filter(c => c.method === 'text').map(c => c.args[0]);
    expect(texts).toContain("CLASS TEACHER'S REMARK:");
    expect(texts).toContain("PRINCIPAL'S COMMENT:");
    expect(texts).toContain('Good progress this term.');
    expect(texts).toContain('Keep it up.');
  });

  test('turning Principal\'s Comment off removes its label AND its box — no blank area left behind', () => {
    const { spy, calls } = makeSpyDoc();
    const sections = computeSections({}, { showPrincipalRemark: false });
    LAYOUTS.legacy_tabular.renderPdf(spy, sections, {}, true);
    const texts = calls.filter(c => c.method === 'text').map(c => c.args[0]);
    expect(texts).not.toContain("PRINCIPAL'S COMMENT:");
    expect(texts).not.toContain('Keep it up.');
    // Class teacher's box is untouched by the other toggle.
    expect(texts).toContain("CLASS TEACHER'S REMARK:");
  });

  test('turning Class Teacher\'s Remark off removes only that box', () => {
    const { spy, calls } = makeSpyDoc();
    const sections = computeSections({}, { showClassTeacherRemark: false });
    LAYOUTS.legacy_tabular.renderPdf(spy, sections, {}, true);
    const texts = calls.filter(c => c.method === 'text').map(c => c.args[0]);
    expect(texts).not.toContain("CLASS TEACHER'S REMARK:");
    expect(texts).toContain("PRINCIPAL'S COMMENT:");
  });

  test('both off removes both, and the signature line moves up to reclaim the space (fewer rect calls at the old Y)', () => {
    const { spy, calls } = makeSpyDoc();
    const sections = computeSections({}, { showClassTeacherRemark: false, showPrincipalRemark: false });
    LAYOUTS.legacy_tabular.renderPdf(spy, sections, {}, true);
    const texts = calls.filter(c => c.method === 'text').map(c => c.args[0]);
    expect(texts).not.toContain("CLASS TEACHER'S REMARK:");
    expect(texts).not.toContain("PRINCIPAL'S COMMENT:");
    expect(texts).not.toContain('Good progress this term.');
    expect(texts).not.toContain('Keep it up.');
  });
});

describe('legacy_tabular.renderHtml — remark boxes now honour their toggles', () => {
  test('both render by default', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections());
    expect(html).toContain('Good progress this term.');
    expect(html).toContain('Keep it up.');
  });

  test('each toggle independently removes its own block, not both', () => {
    const onlyPrincipal = LAYOUTS.legacy_tabular.renderHtml(computeSections({}, { showClassTeacherRemark: false }));
    expect(onlyPrincipal).not.toContain('Good progress this term.');
    expect(onlyPrincipal).toContain('Keep it up.');

    const onlyClassTeacher = LAYOUTS.legacy_tabular.renderHtml(computeSections({}, { showPrincipalRemark: false }));
    expect(onlyClassTeacher).toContain('Good progress this term.');
    expect(onlyClassTeacher).not.toContain('Keep it up.');
  });
});

describe('legacy_tabular — subject names, not raw subjectIds (reported: "just seeing their ids")', () => {
  test('the results table and the subject-comments table both show the resolved name', () => {
    const sections = computeSections({}, {}, { subjectNames: { math: 'Mathematics', english: 'English Language' } });
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html).toContain('Mathematics');
    expect(html).toContain('English Language');
    expect(html).not.toContain('>math<');
    expect(html).not.toContain('>english<');
  });

  test('falls back to the raw id if a subject has no resolvable name (e.g. deleted after the snapshot was taken)', () => {
    const sections = computeSections({}, {}, { subjectNames: {} });
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html).toContain('math');
    expect(html).toContain('english');
  });

  test('same fix applies to the PDF path', () => {
    const { spy, calls } = makeSpyDoc();
    const sections = computeSections({}, {}, { subjectNames: { math: 'Mathematics', english: 'English Language' } });
    LAYOUTS.legacy_tabular.renderPdf(spy, sections, {}, true);
    const texts = calls.filter(c => c.method === 'text').map(c => c.args[0]);
    expect(texts.some(t => String(t).includes('Mathematics'))).toBe(true);
    expect(texts.some(t => String(t) === 'math')).toBe(false);
  });
});

describe('legacy_tabular.renderHtml — Observation Ratings now actually appear', () => {
  test('never shown when the school has not turned it on (default)', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections());
    expect(html).not.toContain('Class Teacher Observations');
  });

  test('shown with the saved rating when turned on', () => {
    const sections = computeSections(
      { comments: { ...baseSnap().comments, observationRatings: { Teamwork: 'good' } } },
      { showObservationRatings: true, observationCategories: ['Teamwork', 'Confidence'] },
    );
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html).toContain('Class Teacher Observations');
    expect(html).toContain('Teamwork');
    expect(html).toContain('Confidence');
  });

  // Reported directly: "Class teacher observation, see the design" — a
  // grid of per-category cards (EXCELLENT/GOOD/IMPROVE checkboxes each),
  // not the old one long category-vs-rating table.
  test('renders as a 3-column card grid, with the selected rating\'s checkbox filled', () => {
    const sections = computeSections(
      { comments: { ...baseSnap().comments, observationRatings: { Teamwork: 'good' } } },
      { showObservationRatings: true, observationCategories: ['Teamwork'] },
    );
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html).toContain('grid-template-columns:repeat(3,1fr)');
    expect(html).toContain('EXCELLENT');
    expect(html).toContain('GOOD');
    expect(html).toContain('IMPROVE');
    // Exactly one of the three checkbox spans for this category is filled.
    const filled = (html.match(/background:#1e293b"><\/span>/g) || []).length;
    expect(filled).toBe(1);
  });

  // Raised directly: "should be grid view just before" — the grid used to
  // render after Subject Teacher Comments; moved ahead of it.
  test('the Observation Ratings grid is positioned before Subject Teacher Comments, not after', () => {
    const sections = computeSections(
      { comments: { ...baseSnap().comments, observationRatings: { Teamwork: 'good' } } },
      { showObservationRatings: true, observationCategories: ['Teamwork'] },
    );
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html.indexOf('Class Teacher Observations')).toBeLessThan(html.indexOf('Subject Teacher Comments'));
  });
});

describe('legacy_tabular.renderHtml — subject teacher name (reported: "no subject teachers name")', () => {
  test('the Subject Teacher Comments table now has its own Teacher column, like the other two layouts', () => {
    const sections = computeSections({}, {}, { subjectTeacherNames: { math: 'Mr. Kamau' } });
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html).toContain('Mr. Kamau');
    expect(html).toContain('>Teacher<'); // the new column header
  });

  test('an unassigned subject shows "Unassigned", not a blank cell', () => {
    const sections = computeSections({}, {}, { subjectTeacherNames: {} });
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html).toContain('Unassigned');
  });
});

describe('legacy_tabular.renderHtml — Behaviour page is skipped, not shown empty', () => {
  test('no forced page, no "No behaviour records" placeholder, when there is nothing to show', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections());
    expect(html).not.toContain('BEHAVIOUR REPORT');
    expect(html).not.toContain('No behaviour records found');
  });

  test('renders normally when there is real behaviour data', () => {
    const sections = computeSections({}, { showBehaviour: true }, {
      behaviour: { merits: 5, demerits: 1, points: 4, total: 6 },
    });
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html).toContain('BEHAVIOUR REPORT');
    expect(html).toContain('Merits');
  });
});

describe('legacy_tabular.renderHtml — no stray "Generated by Msingi" line on the cover', () => {
  test('the cover no longer carries this hardcoded, non-customisable text', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections());
    expect(html).not.toContain('Generated by Msingi');
  });

  test('the shared cover (subject_paired/marks_then_comments) is also clean', () => {
    expect(LAYOUTS.subject_paired.renderHtml(computeSections())).not.toContain('Generated by Msingi');
    expect(LAYOUTS.marks_then_comments.renderHtml(computeSections())).not.toContain('Generated by Msingi');
  });

  test('the real, customisable footer message and date are still present', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections({}, { footerNote: 'This report is unofficial unless signed and/or stamped by a school official.' }));
    expect(html).toContain('This report is unofficial unless signed and/or stamped by a school official.');
    expect(html).toMatch(/Generated:/);
  });
});

// Reported directly, twice: "the second page is blank." Removing the
// stray text line (above) wasn't the whole fix — the cover's own
// min-height was 277mm, 10mm TALLER than the 267mm actually printable
// on an A4 page under this file's own @page{margin:1.5cm} rule (297mm
// page - 2x15mm margins), which guaranteed overflow onto a near-empty
// second page on every print, regardless of content. Pinned here so a
// future edit can't silently reintroduce a min-height at or above 267mm.
describe('cover min-height stays within the actual printable A4 area (267mm under @page{margin:1.5cm})', () => {
  function coverMinHeightMm(html) {
    const m = html.match(/min-height:(\d+)mm/);
    return m ? Number(m[1]) : null;
  }

  test('legacy_tabular', () => {
    const mm = coverMinHeightMm(LAYOUTS.legacy_tabular.renderHtml(computeSections()));
    expect(mm).not.toBeNull();
    expect(mm).toBeLessThan(267);
  });

  test('the shared cover (subject_paired/marks_then_comments)', () => {
    const mmSubjectPaired = coverMinHeightMm(LAYOUTS.subject_paired.renderHtml(computeSections()));
    const mmMarksThen     = coverMinHeightMm(LAYOUTS.marks_then_comments.renderHtml(computeSections()));
    expect(mmSubjectPaired).not.toBeNull();
    expect(mmSubjectPaired).toBeLessThan(267);
    expect(mmMarksThen).toBe(mmSubjectPaired); // same shared cover function
  });
});

describe('legacy_tabular.renderHtml — principal signature & school stamp (reported: "the stamp and principal\'s signature didn\'t show")', () => {
  test('neither image appears when the school has uploaded neither', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections());
    expect(html).not.toContain('<img');
  });

  test('a published snapshot\'s own frozen URLs render as <img> tags', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(
      computeSections({ principalSignatureUrl: 'data:image/png;base64,AAAA', schoolStampUrl: 'data:image/png;base64,BBBB' })
    );
    expect(html).toContain('<img src="data:image/png;base64,AAAA"');
    expect(html).toContain('<img src="data:image/png;base64,BBBB"');
  });

  test('falls back to the live school profile when the snapshot has none of its own (unpublished draft preview)', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(
      computeSections({}, {}, { school: { principalSignatureUrl: 'data:image/png;base64,CCCC', schoolStampUrl: 'data:image/png;base64,DDDD' } })
    );
    expect(html).toContain('<img src="data:image/png;base64,CCCC"');
    expect(html).toContain('<img src="data:image/png;base64,DDDD"');
  });

  test('the snapshot\'s own frozen URL wins over a later live school-profile change', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(
      computeSections(
        { principalSignatureUrl: 'data:image/png;base64,FROZEN' },
        {},
        { school: { principalSignatureUrl: 'data:image/png;base64,CHANGED_SINCE' } },
      )
    );
    expect(html).toContain('<img src="data:image/png;base64,FROZEN"');
    expect(html).not.toContain('CHANGED_SINCE');
  });

  test('turning off Principal\'s Comment removes the signature image too — it has nowhere left to sit', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(
      computeSections({ principalSignatureUrl: 'data:image/png;base64,AAAA', schoolStampUrl: 'data:image/png;base64,BBBB' }, { showPrincipalRemark: false })
    );
    expect(html).not.toContain('<img');
  });

  test('same fix applies to the PDF path', () => {
    const { spy, calls } = makeSpyDoc();
    const sections = computeSections();
    LAYOUTS.legacy_tabular.renderPdf(spy, sections, { principalSignature: Buffer.from('x'), schoolStamp: Buffer.from('y') }, true);
    expect(calls.some(c => c.method === 'image')).toBe(true);
  });
});

describe('principal\'s name — auto-resolves from the school profile (reported: "system should be aware who is the school principal")', () => {
  test('falls back to the school-wide default when no per-report name was typed', () => {
    // baseSnap() defaults comments.principalName to 'Dr. Kariuki' — cleared
    // here so this test actually exercises the "nothing typed" case.
    const sections = computeSections(
      { comments: { ...baseSnap().comments, principalName: '' } },
      {},
      { school: { principalName: 'Dr. Jane Mwangi' } },
    );
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html).toContain('Dr. Jane Mwangi');
  });

  test('a per-report manually-typed name still overrides the school-wide default', () => {
    const sections = computeSections(
      { comments: { ...baseSnap().comments, principalName: 'Mr. Omondi (Acting)' } },
      {},
      { school: { principalName: 'Dr. Jane Mwangi' } },
    );
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html).toContain('Mr. Omondi (Acting)');
    expect(html).not.toContain('Dr. Jane Mwangi');
  });

  test('a published snapshot\'s own frozen schoolPrincipalName is used when no per-report name was typed', () => {
    const sections = computeSections(
      { comments: { ...baseSnap().comments, principalName: '' }, schoolPrincipalName: 'Dr. Jane Mwangi (frozen at publish)' },
      {},
      { school: { principalName: 'Someone Else (changed since)' } },
    );
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html).toContain('Dr. Jane Mwangi (frozen at publish)');
    expect(html).not.toContain('Someone Else');
  });

  test('neither configured — blank, not an error', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections());
    expect(html).toContain('<!DOCTYPE html>');
  });
});

describe('footer timestamp — school-timezone-aware (reported: "configure the time zones... it should be configured in the system")', () => {
  test('formats the generation time in the school\'s own IANA timezone, not raw UTC', () => {
    const sections = computeSections({}, {}, { school: { timezone: 'Africa/Nairobi' } });
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    // Nairobi is UTC+3 — some timezone abbreviation/offset must appear,
    // and it must not be the bare "GMT" a raw toUTCString() would show.
    expect(html).toMatch(/GMT\+3/);
  });

  test('falls back to UTC when the school has no timezone configured', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections());
    expect(html).toMatch(/Generated:.*UTC/);
  });

  test('an invalid/corrupt saved timezone string fails safe to UTC instead of throwing', () => {
    const sections = computeSections({}, {}, { school: { timezone: 'Not/ARealZone' } });
    expect(() => LAYOUTS.legacy_tabular.renderHtml(sections)).not.toThrow();
  });
});

describe('sign-off block — redesigned per a shared reference layout', () => {
  test('a banner header, the role/title below the name (not above), and a Date: line all appear', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections());
    expect(html).toContain("Class Teacher's General Comment");
    expect(html).toContain("Principal's General Comment");
    expect(html).toMatch(/Date: \d{2}\/\d{2}\/\d{4}/);
  });

  test('the term-dates footer bar renders when closing/next-term dates are set', () => {
    const sections = computeSections({ comments: { ...baseSnap().comments, closingDate: '2026-11-28', nextTermBegin: '2027-01-12' } }, {}, {});
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html).toContain('Ended on: 2026-11-28');
    expect(html).toContain('Next Term begins on: 2027-01-12');
  });

  test('the term-dates footer bar is absent when neither date is set', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections());
    expect(html).not.toContain('begins on:');
  });

  test('Sports & Talent still renders as its own field when set', () => {
    const sections = computeSections({ comments: { ...baseSnap().comments, sportsAndTalent: 'Captain of football' } }, {}, {});
    const html = LAYOUTS.legacy_tabular.renderHtml(sections);
    expect(html).toContain('Captain of football');
  });
});

describe('subject_paired/marks_then_comments now also render Sports & Talent and the term-dates bar (previously legacy_tabular-only)', () => {
  test('subject_paired', () => {
    const sections = computeSections({ comments: { ...baseSnap().comments, sportsAndTalent: 'Chess club captain', closingDate: '2026-11-28', nextTermBegin: '2027-01-12' } }, {}, {});
    const html = LAYOUTS.subject_paired.renderHtml(sections);
    expect(html).toContain('Chess club captain');
    expect(html).toContain('Ended on: 2026-11-28');
    expect(html).toContain('Next Term begins on: 2027-01-12');
  });

  test('marks_then_comments', () => {
    const sections = computeSections({ comments: { ...baseSnap().comments, sportsAndTalent: 'Chess club captain', closingDate: '2026-11-28', nextTermBegin: '2027-01-12' } }, {}, {});
    const html = LAYOUTS.marks_then_comments.renderHtml(sections);
    expect(html).toContain('Chess club captain');
    expect(html).toContain('Ended on: 2026-11-28');
    expect(html).toContain('Next Term begins on: 2027-01-12');
  });
});

describe('cover header — redesigned per a shared reference layout (logo left, contact info stacked right)', () => {
  function sectionsWithSchool(extraSchool) {
    return computeSections({}, {}, { school: { logoUrl: null, tagline: 'Excellence in all we do', address: '123 Main St', phone: '0700 000000', email: 'info@school.ac.ke', website: 'www.school.ac.ke', ...extraSchool } });
  }

  test('legacy_tabular cover now shows address/phone/email — previously showed none at all', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(sectionsWithSchool());
    expect(html).toContain('123 Main St');
    expect(html).toContain('0700 000000');
    expect(html).toContain('info@school.ac.ke');
  });

  test('the shared cover (subject_paired/marks_then_comments) also shows them', () => {
    const html = LAYOUTS.subject_paired.renderHtml(sectionsWithSchool());
    expect(html).toContain('123 Main St');
    expect(html).toContain('0700 000000');
  });

  test('no school contact info configured — blank, not an error', () => {
    const html = LAYOUTS.legacy_tabular.renderHtml(computeSections());
    expect(html).toContain('<!DOCTYPE html>');
  });
});
